import type { Config } from '@/types/config'
import type { Context } from '@/types/context'
import type { Manifest } from '@/types/manifest'
import type { CommandModule } from '@/types/command'

import { parseAndCoerce } from '@/core/parser'
import { buildRouteLookup, resolveRoute } from '@/core/router'
import { createIo, createLogger } from '@/io/index'

/**
 * Build a Manifest from a flat map of `route -> command module`.
 *
 * Routes are slash-delimited (`'users/list'` becomes `['users', 'list']`), which
 * is exactly what the router's longest-prefix matcher expects. In a real project
 * this manifest is code-generated by scanning the commands directory; demos and
 * tests build it inline so everything stays in one readable file.
 */
export function defineManifest(routes: Record<string, CommandModule>): Manifest {
  return {
    entries: Object.entries(routes).map(([key, module]) => ({
      route: key.split('/'),
      sourcePath: `${key}.ts`,
      importer: () => Promise.resolve({ default: module }),
      meta: module.meta,
    })),
  }
}

/**
 * Resolve argv against the manifest, parse flags, build the context, and run the
 * matched command. Returns the process exit code (the command's numeric return,
 * or 0). This is the same dispatch the Phase 0 spike proved out, factored into a
 * reusable function so each entry point (and every demo) is a few lines.
 */
export async function run(
  manifest: Manifest,
  config: Config,
  argv: string[] = Bun.argv.slice(2),
): Promise<number> {
  const io = createIo(),
    logger = createLogger()

  const match = resolveRoute(argv, buildRouteLookup(manifest))

  if (!match) {
    io.writeError(`Unknown command: ${argv.join(' ') || '(none)'}`)
    return 1
  }

  const { entry, remaining } = match,
    command = (await entry.importer()).default

  try {
    const parsed = parseAndCoerce(remaining, command.flags ?? {}),
      context: Context = {
        flags: parsed.values,
        positionals: parsed.positionals,
        route: entry.route,
        cwd: process.cwd(),
        env: process.env as Record<string, string | undefined>,
        config,
        io,
        logger,
      }

    const result = await command.run(context)

    return typeof result === 'number' ? result : 0
  } catch (error) {
    io.writeError(`Error: ${error instanceof Error ? error.message : String(error)}`)

    return 1
  }
}
