import { existsSync } from 'node:fs'
import { join, dirname } from 'node:path'

import type { Config } from '@/types/config'
import type { Context } from '@/types/context'
import type { Manifest } from '@/types/manifest'
import type { CommandModule } from '@/types/command'

import { parseAndCoerce } from '@/core/parser'
import { discoverManifest } from '@/core/discovery'
import { buildRouteLookup, resolveRoute } from '@/core/router'
import { createIo, createLogger } from '@/io/index'

/**
 * Build a Manifest from a flat map of `route -> command module`.
 *
 * Routes are slash-delimited (`'users/list'` becomes `['users', 'list']`), which
 * is exactly what the router's longest-prefix matcher expects. In a real project
 * this manifest is code-generated by scanning the commands directory; demos and
 * tests build it inline so everything stays in one readable file.
 */
export function defineManifest(routes: Record<string, CommandModule>): Manifest {
  return {
    entries: Object.entries(routes).map(([key, module]) => ({
      route: key.split('/'),
      sourcePath: `${key}.ts`,
      importer: () => Promise.resolve({ default: module }),
      meta: module.meta,
    })),
  }
}

/**
 * Dispatch a command using `config.manifest` if present, otherwise auto-discover
 * one from `config.commandsDir`, resolved relative to the caller's location
 * (`importMeta.dir`). `importMeta` is only required when discovery is needed.
 *
 * Sets `process.exitCode` to the resolved code so entrypoints can just call
 * `void run(config)` instead of `process.exit(await run(config))`.
 */
export async function run(
  config: Config,
  importMeta?: { dir: string },
  argv?: string[],
): Promise<number> {
  const exitCode = await dispatch(config, importMeta, argv)

  process.exitCode = exitCode
  return exitCode
}

async function dispatch(
  config: Config,
  importMeta?: { dir: string },
  argv?: string[],
): Promise<number> {
  let manifest: Manifest

  if (config.manifest) {
    manifest = config.manifest
  } else {
    if (!importMeta?.dir) {
      console.error(
        'Error: discovering commands from config.commandsDir requires passing import.meta (with a dir) as the second argument to run().',
      )

      return 1
    }

    // Auto-discover manifest from config.commandsDir
    const commandsDir = config.commandsDir ?? 'commands'
    let resolvedCommandsDir = join(importMeta.dir, commandsDir)

    // If commands dir doesn't exist, try looking in the parent directory
    // (handles case where CLI entrypoint is in a subdirectory but commands is at the project root)
    if (!existsSync(resolvedCommandsDir)) {
      const parentDir = dirname(importMeta.dir),
        parentCommandsDir = join(parentDir, commandsDir)

      if (existsSync(parentCommandsDir)) resolvedCommandsDir = parentCommandsDir
    }

    try {
      manifest = await discoverManifest(resolvedCommandsDir)
    } catch (error) {
      console.error(
        `Error: failed to discover commands in "${resolvedCommandsDir}": ${error instanceof Error ? error.message : String(error)}`,
      )
      return 1
    }
  }

  const resolvedArgv = argv ?? Bun.argv.slice(2)

  const io = createIo(),
    logger = createLogger()

  // Use name as default for bin if not provided
  if (!config.bin) config.bin = config.name

  const match = resolveRoute(resolvedArgv, buildRouteLookup(manifest))

  if (!match) {
    io.writeError(`Unknown command: ${resolvedArgv.join(' ') || '(none)'}`)
    return 1
  }

  const { entry, remaining } = match,
    command = (await entry.importer()).default

  try {
    const parsed = parseAndCoerce(remaining, command.flags ?? {}),
      context: Context = {
        flags: parsed.values,
        positionals: parsed.positionals,
        route: entry.route,
        cwd: process.cwd(),
        env: process.env as Record<string, string | undefined>,
        config,
        io,
        logger,
      }

    const result = await command.run(context)

    return typeof result === 'number' ? result : 0
  } catch (error) {
    io.writeError(`Error: ${error instanceof Error ? error.message : String(error)}`)

    return 1
  }
}
