import { join, dirname } from 'node:path'
import { existsSync } from 'node:fs'

import type { Config } from '@/types/config'
import type { Context } from '@/types/context'
import type { Manifest } from '@/types/manifest'
import type { CommandModule } from '@/types/command'

import { parseAndCoerce } from '@/core/parser'
import { buildRouteLookup, resolveRoute } from '@/core/router'
import { createIo, createLogger } from '@/io/index'
import { discoverManifest } from '@/core/discovery'

/**
 * Build a Manifest from a flat map of `route -> command module`.
 *
 * Routes are slash-delimited (`'users/list'` becomes `['users', 'list']`), which
 * is exactly what the router's longest-prefix matcher expects. In a real project
 * this manifest is code-generated by scanning the commands directory; demos and
 * tests build it inline so everything stays in one readable file.
 */
export function defineManifest(routes: Record<string, CommandModule>): Manifest {
  return {
    entries: Object.entries(routes).map(([key, module]) => ({
      route: key.split('/'),
      sourcePath: `${key}.ts`,
      importer: () => Promise.resolve({ default: module }),
      meta: module.meta,
    })),
  }
}

/**
 * Dispatch a command from an automatically discovered manifest.
 * The manifest is discovered from the commandsDir in config, resolved relative
 * to the caller's location (import.meta.dir).
 */
export async function run(
  config: Config,
  importMeta: { dir: string },
  argv?: string[],
): Promise<number>

/**
 * Dispatch a command from an explicit manifest.
 * Kept for backwards compatibility and for tests that build manifests inline.
 */
export async function run(
  manifest: Manifest,
  config: Config,
  argv?: string[],
): Promise<number>

export async function run(
  configOrManifest: Config | Manifest,
  configOrImportMeta?: Config | { dir: string },
  argv?: string[],
): Promise<number> {
  // Determine if we received (manifest, config, argv) or (config, import.meta, argv)
  const isFirstArgManifest = 'entries' in configOrManifest

  let manifest: Manifest
  let config: Config
  let resolvedArgv: string[]

  if (isFirstArgManifest) {
    // Old signature: (manifest, config, argv)
    manifest = configOrManifest as Manifest
    config = configOrImportMeta as Config
    resolvedArgv = argv ?? Bun.argv.slice(2)
  } else {
    // New signature: (config, import.meta, argv)
    config = configOrManifest as Config
    const importMeta = configOrImportMeta as { dir: string }
    resolvedArgv = argv ?? Bun.argv.slice(2)

    // Auto-discover manifest from config.commandsDir
    const commandsDir = config.commandsDir ?? 'commands'
    let resolvedCommandsDir = join(importMeta.dir, commandsDir)

    // If commands dir doesn't exist, try looking in the parent directory
    // (handles case where CLI is in src/cli.ts but commands is at root)
    if (!existsSync(resolvedCommandsDir)) {
      const parentDir = dirname(importMeta.dir)
      const parentCommandsDir = join(parentDir, commandsDir)
      if (existsSync(parentCommandsDir)) {
        resolvedCommandsDir = parentCommandsDir
      }
    }

    manifest = await discoverManifest(resolvedCommandsDir)
  }

  const io = createIo(),
    logger = createLogger()

  const match = resolveRoute(resolvedArgv, buildRouteLookup(manifest))

  if (!match) {
    io.writeError(`Unknown command: ${resolvedArgv.join(' ') || '(none)'}`)
    return 1
  }

  const { entry, remaining } = match,
    command = (await entry.importer()).default

  try {
    const parsed = parseAndCoerce(remaining, command.flags ?? {}),
      context: Context = {
        flags: parsed.values,
        positionals: parsed.positionals,
        route: entry.route,
        cwd: process.cwd(),
        env: process.env as Record<string, string | undefined>,
        config,
        io,
        logger,
      }

    const result = await command.run(context)

    return typeof result === 'number' ? result : 0
  } catch (error) {
    io.writeError(`Error: ${error instanceof Error ? error.message : String(error)}`)

    return 1
  }
}
